// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fghlgdkrizcidzzpfffk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnaGxnZGtyaXpjaWR6enBmZmZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0ODI0OTMsImV4cCI6MjA2MTA1ODQ5M30.7mqjS9ZCMIFeoMJdfLo9EEFCXkWuQXGZRqkTPRuOT7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);